from abc import ABC, abstractmethod


class AIProvider(ABC):
    @abstractmethod
    def get_provider_name(self) -> str: ...
    @abstractmethod
    def test_connection(self) -> bool: ...
    @abstractmethod
    def get_available_models(self) -> list[str]: ...
    @abstractmethod
    def translate_batch(self, entries: list[dict], target_language: str) -> list[dict]: ...
    @abstractmethod
    def analyze_conflict(self, payload: dict) -> dict: ...
    @abstractmethod
    def cancel(self) -> None: ...
